name: Docker image Build Test

on:
  push:
    branches:
      - 'fix/**'
      - docker-stacks/update
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Dockerfile
        shell: bash
        run: |
          python generate_Dockerfile.py
      - name: Declare commit hash variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .build/
          push: false
          tags: n0k0m3/rapidsai-spark-notebook:${{ steps.vars.outputs.sha_short }}
          load: true
      - name: Test docker image
        run: |
          docker run -d --rm n0k0m3/rapidsai-spark-notebook:${{ steps.vars.outputs.sha_short }}
