name: Docker image Build Test

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Declare branch and commit hash variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .build/
          push: false
          tags: n0k0m3/pyspark-notebook-deltalake:${{ steps.vars.outputs.branch }}.${{ steps.vars.outputs.sha_short }}
