name: Update jupyter docker-stack Dockerfile

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  check-update:
    name: Generate Dockerfile parts from source jupyter/docker-stacks
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clone and generate docker-stacks parts
        shell: bash
        run: |
          python source_Dockerfile_parts.py
      - name: Declare docker-stacks commit hash variables
        id: docker-stacks
        shell: bash
        run: |
          cd docker-stacks
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Commit generated Dockerfile parts if changed
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Update jupyter docker-stack Dockerfile parts based on upstream source ${{ steps.docker-stacks.outputs.sha_short }}
          new_branch: docker-stacks_${{ steps.docker-stacks.outputs.sha_short }}
          push: true
